services:
  admin-2-vite:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
      target: node
    pull_policy: always
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SHM_HOST: http://host.docker.internal:8080
      VITE_SHOW_SWAGGER: "true"
      VITE_BASE_PATH: /
    expose:
      - "5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public

  admin-2-nginx:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
      target: admin-2-nginx
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - VITE_HOST=admin-2-vite
      - VITE_SHOW_SWAGGER=true
      - SHM_HOST=http://host.docker.internal:8080
      - SHM_BASE_PATH=/
    ports:
      - "8081:80"
    depends_on:
      - admin-2-vite
